---
abstract: 'basic functions for the BioStudio synthetic biology framework'
author:
  - 'Sarah Richardson <notadoctor@jhu.edu>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BioStudio-Basic
provides:
  BioStudio::BLAST:
    file: lib/BioStudio/BLAST.pm
    version: 1.00
  BioStudio::Basic:
    file: lib/BioStudio/Basic.pm
    version: 1.00
  BioStudio::Diff:
    file: lib/BioStudio/Diff.pm
    version: 1.00
  BioStudio::Foswiki:
    file: lib/BioStudio/Foswiki.pm
    version: 1.00
  BioStudio::GBrowse:
    file: lib/BioStudio/GBrowse.pm
    version: 1.00
  BioStudio::GFF3:
    file: lib/BioStudio/GFF3.pm
    version: 1.00
  BioStudio::MySQL:
    file: lib/BioStudio/MySQL.pm
    version: 1.00
requires:
  Bio::DB::SeqFeature::Store: 0
  Bio::Seq: 0
  Bio::SeqIO: 0
  Config::Auto: 0.38
  DBI: 1.616
  Digest::MD5: 2.51
  GeneDesign::Basic: 0
  Perl6::Slurp: 0.03
  Text::Diff: 1.3
  Text::Wrap: 2009.0305
  Time::Format: 1.11
  URI::Escape: 1.59
  perl: 5.006
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1.00
